import fs from 'node:fs';
import path from 'node:path';

export interface CountryImageInfo {
  continent: string;
  flag: string | null;
  stamp: string | null;
}

let cache: Record<string, CountryImageInfo> | null = null;

/**
 * Per-country flag + passport-stamp image paths (relative to /images/),
 * generated by `_migration/consolidate_country_images.py` into
 * public/images/countries/manifest.json. Read once and cached — this file
 * doesn't change at runtime.
 */
export function getCountryImages(): Record<string, CountryImageInfo> {
  if (!cache) {
    const manifestPath = path.join(process.cwd(), 'public/images/countries/manifest.json');
    cache = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));
  }
  return cache!;
}
