import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  site: 'https://intothegreatwideopen.com',
  trailingSlash: 'ignore',
  vite: {
    build: {
      rollupOptions: {
        // /pagefind/pagefind.js is generated by the `pagefind` CLI step
        // that runs *after* `astro build` (see package.json's "build"
        // script and src/pages/search.astro) — it doesn't exist yet at
        // the point Vite/Rollup bundles the client script that imports
        // it, so it must be excluded from build-time resolution entirely
        // and left as a plain runtime import for the browser to resolve
        // once the real file exists in the deployed dist/ output.
        external: ['/pagefind/pagefind.js'],
      },
    },
  },
});
